con4gisGroupsBundle:
    path: /con4gis/api/{_url_fragment}
    defaults:
        _scope: frontend
        _controller: "con4gisGroupsBundle:Ajax:ajax"
    requirements:
        module: '\d+'
        action: '.*'

