con4gisGroupsBundle:
    path: /con4gis/groupsService/{id}/{req}
    defaults:
        _scope: frontend
        _controller: "con4gisGroupsBundle:Groups:run"
    requirements:
        id: \d+
        req: .*

inviteMember:
    path: /con4gis/inviteMember/{memberEmail}/{groupId}
    defaults:
        _scope: frontend
        _controller: "con4gisGroupsBundle:Api:inviteMember"


removeMember:
    path: /con4gis/removeMember/{groupId}/{memberId}
    defaults:
        _scope: frontend
        _controller: "con4gisGroupsBundle:Api:removeMemberFromGroup"
    methods: [DELETE]