services:
  _defaults:
    autowire: true
    autoconfigure: true

  con4gis\GroupsBundle\Controller\ApiController:
    class: con4gis\GroupsBundle\Controller\ApiController
    public: true
    arguments:
      - "@service_container"

  con4gis\GroupsBundle\Controller\GroupsController:
    class: con4gis\GroupsBundle\Controller\GroupsController
    public: true
    arguments:
      - "@contao.framework"
  con4gis\GroupsBundle\Classes\Notifications\:
    resource: '../../Classes/Notifications'
    autoconfigure: true
    autowire: true
